♻️  Refactor : 유저 이미지 DTO 변경
Like-House/BE pull request #117
Opened 2024-08-05 12:13 UTC by jiinkyung

# 💡 PR Summary - 유저 이미지 DTO 변경

### 📝 Description

---

유저 이미지와 관련한 dto를 keyname으로 변경하였습니다.
이미지를 받아올 때 @CheckImageKeyName을 추가하였습니다.

### 🌲 Working Branch

---

refactor/#110

### 📖 Related Issues

---

#110 

### 📚 Etc

---

특이사항

2024-08-05 13:23 UTC, dabeann approved these changes

2024-08-06 06:23 UTC, catturtle123 requested changes

2024-08-06 06:23 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/user/dto/UserDTO.java
> +        @CheckImageKeyName
response에는 필요 없는 것 같습니다.

2024-08-06 06:23 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/user/dto/UserDTO.java
> -        private String profileImage;
여기에 필요한 것 같습니다.

2024-08-06 06:23 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
> +        private String imageKeyName;
여기에 필요할 것 같습니다.

2024-08-06 10:53 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/auth/dto/AuthDTO.java
> +        private String imageKeyName;
수정 완료하였습니다~~!

2024-08-06 12:06 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-08-06 14:17 UTC, merged