✨ Feature : 회원가입/로그인 구현
Like-House/BE pull request #14
Opened 2024-07-16 17:17 UTC by jiinkyung

# 💡 PR Summary - JWT 회원가입/로그인 구현

### 📝 Description
---

JWT를 이용한 회원가입 및 로그인 로직을 구현하였습니다.

### 🌲 Working Branch

---

feature/#9

### 📖 Related Issues

---

1. 우선 로컬에서 회원가입 및 로그인, refreshToken Redis에 잘 저장되는 것 확인했습니다.
2. signUp, signIn의 response 타입 확인 부탁드립니다.
3. 회원가입 과정에서의 프로필 이미지의 경우, 아직 순수 string 값으로 넣도록 되어 있습니다. 추후 수정하겠습니다.

### 📚 Etc

---

아직 리팩토링 해야 할 부분이 있는데, 다른 분들의 개발을 위해서 최대한 빠르게 올립니다!! 참고 부탁드립니다
마구마구 지적 부탁드려요..

2024-07-16 18:06 UTC, dabeann commented on src/main/java/backend/like_house/domain/user/dto/SignInDTO.java
DTO파일 두개 하나로 합치는 건 어떤가요??? 

그리고 request에는 Getter 어노테이션만 있으면 될 것 같고
response에는 Data 어노테이션 빼고 Getter 넣어주시면 좋겠습니다!

2024-07-16 18:06 UTC, dabeann commented on src/main/java/backend/like_house/domain/user/service/impl/UserCommandServiceImpl.java
서비스 클래스의 Transactional 어노테이션은 어느 부분 때문에 넣으신 걸까요?

2024-07-16 18:06 UTC, dabeann commented on src/main/java/backend/like_house/global/redis/Redis.java
Setter 말구 Builder로는 처리 안될까요?!

2024-07-16 18:06 UTC, dabeann commented on src/main/java/backend/like_house/domain/user/controller/UserController.java
UserController 접근제어자, 각 api 메소드 접근제어자 `public`빼는 것 어떤가요?

2024-07-17 05:50 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/user/dto/SignInDTO.java
저도 두 개 파일 합치는 것을 고려하긴 했었는데 클래스명을 고민하다가 나눠버렸습니다... 😓 
다른 분들의 의견도 궁금합니다!! @catturtle123 @haeun1107

어노테이션 관련한 부분은 수정하겠습니다!

2024-07-17 05:51 UTC, jiinkyung commented on src/main/java/backend/like_house/global/redis/Redis.java
넵넵 builder로 수정하겠습니다!

2024-07-17 05:59 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/user/service/impl/UserCommandServiceImpl.java
이 부분은 서비스 레이어가 실행되고 DB에 작업이 일어날 때 일관성 유지가 필요할 것 같다고 생각해서 추가했습니다. 
의견 편하게 말씀해주세요~~

2024-07-17 06:04 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/user/controller/UserController.java
혹시 접근제어자를 빼는 이유는 뭘까요??

2024-07-17 06:12 UTC, catturtle123 requested changes

2024-07-17 06:12 UTC, catturtle123 commented on src/main/resources/application-jwt.yml
> +spring:
elastic beanstalk에 키값 추가 시켜 주세요

2024-07-17 06:12 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                        Authentication authentication = jwtUtil.getAuthentication(jwtUtil.extractEmail(refreshedAccessToken));
현재는 email로 되어 있는데 소셜 로그인을 한다면 바꾸어야할 수도 있어요 그 부분은 유의하여 주세요 나중에 하면서 바꾸어보시면 될 것 같습니다.

2024-07-17 06:12 UTC, catturtle123 commented on src/main/java/backend/like_house/global/redis/RedisUtil.java
> +    public void saveRefreshToken(String email, String refreshToken) {
현재 access 토큰으로 저장하는 것으로 보이는 데 email이라는 변수의 이름은 고쳐야할 것 같습니다.

2024-07-17 06:12 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                if (refreshToken != null && refreshToken.startsWith("Bearer ")) {
redis에 해당 refresh token이 있는 지 확인하는 로직도 필요할 것 같습니다. 또한 access token이 바뀌는 과정에서 redis의 키값과 다시 사용자에게 가는 키값이 달라지는 괴리가 발생합니다. 이 부분도 생각해주세요.

2024-07-17 06:13 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/user/dto/SignInDTO.java
넵! 저는 합쳐도 괜찮다고 생각합니다! 저는 좋습니다!

2024-07-17 06:24 UTC, jiinkyung commented on src/main/resources/application-jwt.yml
> +spring:
넵~ beanstalk에는 반영해두었습니다.

2024-07-17 06:25 UTC, jiinkyung commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                        Authentication authentication = jwtUtil.getAuthentication(jwtUtil.extractEmail(refreshedAccessToken));
넵..... 고려해서 개발 해보겠습니다!

2024-07-17 06:25 UTC, jiinkyung commented on src/main/java/backend/like_house/global/redis/RedisUtil.java
> +    public void saveRefreshToken(String email, String refreshToken) {
헉 넵넵 반영하겠습니다.

2024-07-17 06:26 UTC, jiinkyung commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                if (refreshToken != null && refreshToken.startsWith("Bearer ")) {
그렇네요.. 어차피 중복되는 이메일로 가입이 안 되도록 되어 있는데, 그렇다면 redis 키 값을 이메일로 하는 것은 어떤가요?

2024-07-17 07:01 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                if (refreshToken != null && refreshToken.startsWith("Bearer ")) {
그래도 될것 같습니다!

2024-07-17 10:56 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                if (refreshToken != null && refreshToken.startsWith("Bearer ")) {
> 그렇네요.. 어차피 중복되는 이메일로 가입이 안 되도록 되어 있는데, 그렇다면 redis 키 값을 이메일로 하는 것은 어떤가요? 

Redis 토큰 검증이 아직 안된 것 같습니다. 그리고 나중에 만약 email에서 다른 키값으로 바꾼다면 redis 키값도 바꾸어야하니 이점을 생각하고 있어주세요!

2024-07-17 11:36 UTC, dabeann commented on src/main/java/backend/like_house/domain/user/service/impl/UserCommandServiceImpl.java
넹 답변 감사합니다
그대로 유지하면 될 것 같아요!

2024-07-17 11:38 UTC, dabeann commented on src/main/java/backend/like_house/domain/user/controller/UserController.java
다른 클래스에서 사용하지 않아서 빼는게 좋다고 생각했었어요~
하지만 준환님이 말씀하신대로 aop사용시 public이 좋다고 하니 유지하면 될 것 같네요!

2024-07-17 13:16 UTC, dabeann approved these changes
👍

2024-07-17 13:23 UTC, catturtle123 requested changes
추가로 인증, 인가 실패시에도 응답통일을 해주어야할 것 같습니다.

2024-07-17 13:23 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +        response.getWriter().write("{\"error\": \"" + message + "\"}");
error도 응답 통일이 필요할 것 같습니다.

2024-07-17 13:43 UTC, jiinkyung commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +        response.getWriter().write("{\"error\": \"" + message + "\"}");
넵 ! 반영했습니다~~

2024-07-17 14:17 UTC, catturtle123 requested changes

2024-07-17 14:17 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                        throw new GeneralException(ErrorStatus.INVALID_REFRESH_TOKEN);
이거 filter는 controlleradvice에서는 못 잡아서 500에러 떠요! 그래서 앞에 Exception을 잡아주는 필터를 만들어주거나 해주어야해요!

2024-07-17 14:17 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                throw new GeneralException(ErrorStatus._BAD_REQUEST);
GeneralException 보다는 스터디북 처럼 따로 Exception이나 handler를 만들어주는 것이 좋을 것 같습니다.

2024-07-17 14:17 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                if (email != null && SecurityContextHolder.getContext().getAuthentication() == null) {
인증 인가 예외 처리의 경우 AccessDeniedHandler하고 AuthenticationEntryPoint를 구현하면 됩니다!

2024-07-17 17:03 UTC, jiinkyung commented on src/main/java/backend/like_house/global/security/filter/JwtAuthenticationFilter.java
> +                if (email != null && SecurityContextHolder.getContext().getAuthentication() == null) {
exceptionFilter, customexception, 인증 및 인가 예외처리 모두 구현하여 반영하였습니다~!

2024-07-17 19:38 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/user/dto/SignInDTO.java
저도 합치는 것이 좋아보입니다 !!!

2024-07-18 01:43 UTC, catturtle123 requested changes

2024-07-18 01:43 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtExceptionFilter.java
> +                                 UserException e) throws IOException {
IoException 에러 시 잡아줄 에러 핸들러가 필요합니다

2024-07-18 01:43 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/user/dto/UserDTO.java
> +    public static class SignInResponse {
로그인 시에 refreshtoken도 넘겨야합니다

2024-07-18 01:43 UTC, catturtle123 commented on src/main/java/backend/like_house/global/redis/Redis.java
> +    private String accessToken;
Email로 바꾸어야할 것같습니다

2024-07-18 08:27 UTC, jiinkyung commented on src/main/java/backend/like_house/global/security/filter/JwtExceptionFilter.java
> +                                 UserException e) throws IOException {
IOException과 그 외의 exception까지도 잡히게 코드 추가하였습니다! 확인 부탁드려요

2024-07-18 08:28 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/user/dto/UserDTO.java
> +    public static class SignInResponse {
반영하였습니다 👍

2024-07-18 08:28 UTC, jiinkyung commented on src/main/java/backend/like_house/global/redis/Redis.java
> +    private String accessToken;
제가 놓쳤네요.. 반영 완료입니다~

2024-07-18 11:11 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/filter/JwtExceptionFilter.java
> +                                 UserException e) throws IOException {
@jiinkyung 
마지막으로 IOException을 그대로 빼는 것 보다는 500에러를 따로 userexception에서 따로빼서 하는 것이 좋을 것 같구요. (parsing오류로 해서) 그리고 모든 Exception을 잡는 것은 빼도 좋을 것 같습니다.

2024-07-18 12:42 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-07-18 13:32 UTC, merged