♻️ Refactor : 일반로그인 이후 JWT를 쿠키로 반환하도록 수정
Like-House/BE pull request #158
Opened 2024-08-10 15:41 UTC by jiinkyung

# 💡 PR Summary - 일반로그인 이후 JWT를 쿠키로 반환하도록 수정

### 📝 Description

---

일반로그인 이후 JWT를 쿠키로 반환하도록 수정했습니다.
인가 과정에서 헤더 검증하는 부분 제외하고 모두 쿠키 검증하는 로직으로 수정하였습니다.

### 🌲 Working Branch

---

refactor/#157

### 📖 Related Issues

---

#157 

### 📚 Etc

---

특이사항

2024-08-10 23:42 UTC, dabeann approved these changes

2024-08-11 06:50 UTC, catturtle123 requested changes

2024-08-11 06:50 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/util/JWTUtil.java
> +        cookie.setMaxAge(maxAge);
secret은 true로 samesite옵션은 none으로 해주세요

2024-08-11 07:49 UTC, catturtle123 commented on src/main/java/backend/like_house/global/security/util/JWTUtil.java
> +        cookie.setMaxAge(maxAge);
그리고 secure도 true로 바꾸어주세요

2024-08-11 08:00 UTC, jiinkyung commented on src/main/java/backend/like_house/global/security/util/JWTUtil.java
> +        cookie.setMaxAge(maxAge);
수정하였습니다 !

2024-08-11 08:00 UTC, catturtle123 approved these changes
고생하셨습니다!

2024-08-11 08:01 UTC, merged