✨ Feature : S3 설정
Like-House/BE pull request #19
Opened 2024-07-17 19:37 UTC by haeun1107

# 💡 PR Summary - S3 설정 

### 📝 Description
---

S3 관련 yml 파일 설정, S3에 파일을 업로드하고 삭제하는 manager를 작성하였습니다.

### 🌲 Working Branch

---

feature/#18 

### 📖 Related Issues
---

#18 

### 📚 Etc

---

특이사항

2024-07-18 09:54 UTC, catturtle123 requested changes

2024-07-18 09:54 UTC, catturtle123 commented on src/main/resources/application-s3.yml
> +spring:
이 부분은 local과 dev과 모두 같은 부분이니 on-profile은 빼주셔도 될 것 같습니다. 또한 elastic beanstalk에 키값 추가 시켜주세요

2024-07-18 09:54 UTC, catturtle123 commented on src/main/java/backend/like_house/global/s3/S3Manager.java
> +            throw new RuntimeException("Error converting multipartFile to file", e);
runtimeException 보다는 스터디북 처럼 직접 exception을 만들어서 하는 것이 좋아 보입니다

2024-07-20 05:07 UTC, haeun1107 commented on src/main/java/backend/like_house/global/s3/S3Manager.java
> +            throw new RuntimeException("Error converting multipartFile to file", e);
네! 수정하겠습니다

2024-07-20 05:07 UTC, haeun1107 commented on src/main/resources/application-s3.yml
> +spring:
네 감사합니다!

2024-07-20 12:28 UTC, dabeann approved these changes

2024-07-20 16:09 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-07-24 11:24 UTC, merged