📝 Docs : 서비스 이용 Swagger
Like-House/BE pull request #21
Opened 2024-07-18 13:13 UTC by dabeann

# 💡 PR Summary - 서비스 이용 Swagger

### 📝 Description

---

서비스 이용 관련 기등들 Swagger 작성

### 🌲 Working Branch

---

docs/#10

### 📖 Related Issues

---

#10

### 📚 Etc

---

특이사항

2024-07-19 06:44 UTC, catturtle123 requested changes

2024-07-19 06:44 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
> +    @GetMapping("/generate/{userId}")
POST가 좋아보입니다.

2024-07-19 06:44 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
> +    @GetMapping("/check/{userId}")
약간 애매한데 확인하는 API도 POST 어떤가요?

2024-07-19 11:23 UTC, dabeann commented on src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
> +    @GetMapping("/generate/{userId}")
네 수정하였습니다!!

2024-07-19 11:23 UTC, dabeann commented on src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
> +    @GetMapping("/check/{userId}")
좋아요 post mappping으로 변경하였습니다~

2024-07-19 13:40 UTC, jiinkyung approved these changes
확인했습니다! 👍

2024-07-20 16:08 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-07-20 17:52 UTC, merged