📝 Docs : 게시글 Swagger
Like-House/BE pull request #25
Opened 2024-07-20 06:53 UTC by haeun1107

# 💡 PR Summary - 게시글 Swagger 

### 📝 Description
---

게시글 관련 기능들 Swagger 작성

### 🌲 Working Branch
---

docs/#15 

### 📖 Related Issues

---

#15 

### 📚 Etc

---

알림 끄기, 키기는 잘 모르겠어서 ... 남겨두었습니다!

2024-07-20 12:36 UTC, dabeann reviewed
request에는 Getter 어노테이션 빼고 다 삭제해주세요~~
또한 컨트롤러에서 @ ApiResponses 를 써서 성공이나 에러 반환 나타내 주면 좋을 것 같아요~

2024-07-20 13:03 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
설정 페이지에 있는 "내가 쓴 글 조회" 기능도 해주셔야 할 것 같아요~

2024-07-21 12:09 UTC, catturtle123 requested changes
현재 comment에만 review를 달았는데 나머지 부분도 수정해서 다시 커밋해주세요

2024-07-21 12:09 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +@RequestMapping("/api/v0/comment")
Api의 명사에는 s를 붙여주세요!

2024-07-21 12:09 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PostMapping("/create/{userId}")
동사는 필요없을 땐 쓰면 안됩니다 create없애주시고 userId는 토큰으로 받아주세요!

2024-07-21 12:09 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PutMapping("/update/{commentId}/{userId}")
update도 위와 같은 이유로 없애주세요!

2024-07-21 12:09 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @DeleteMapping("/delete/{commentId}/{userId}")
delete 없애주세요 userId도요!

2024-07-23 08:29 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
넵!!!

2024-07-23 08:30 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +@RequestMapping("/api/v0/comment")
확인했습니다!!!!!

2024-07-23 13:35 UTC, dabeann approved these changes

2024-07-23 15:05 UTC, jiinkyung approved these changes
👍

2024-07-24 11:41 UTC, closed without merging