📝 Docs : 가족 앨범 Swagger
Like-House/BE pull request #26
Opened 2024-07-20 09:54 UTC by haeun1107

# 💡 PR Summary - 가족 앨범 Swagger 

### 📝 Description

---

가족 앨범 관련 기능들 Swagger 작성

### 🌲 Working Branch

---

docs/#16

### 📖 Related Issues

---

#16 

### 📚 Etc

---

특이사항

2024-07-20 12:40 UTC, dabeann reviewed
여기도 request에는 Getter빼고 다 삭제해주시구요
컨트롤러에서 성공, 에러 반환 @ ApiResponses로 표시 부탁드려요.

그리고 CommentDTO.CommentResponse.CreateCommentResponse 이렇게 메소드안에 쓰이는거 static import하면 메소드안에서 CreateCommentResponse만 쓰면돼서 가독성 더 좋아질 것 같아요~

2024-07-21 12:17 UTC, catturtle123 requested changes

2024-07-21 12:17 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +@RequestMapping("/api/v0/comment")
명사에는 s달아주세요

2024-07-21 12:17 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PostMapping("/create/{userId}")
게시글 쪽에도 리뷰 달아놓았는데 반영해서 모두 고친후 푸시 해주세요

2024-07-23 09:40 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PostMapping("/create/{userId}")
네 알겠습니다!!

2024-07-23 09:40 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +@RequestMapping("/api/v0/comment")
네~!!

2024-07-23 11:39 UTC, dabeann requested changes

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PutMapping("/{commentId}/{userId}")
여기 userId PathVariable은 무슨 유저 아이디인가요??

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @DeleteMapping("/{commentId}/{userId}")
여기 userId도 빼셔야 할 것 같아요

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/home/{familySpaceId}/{userId}")
userId 지우셔야 할 것 같아요~

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/detail/{postId}/{userId}")
여기 userId도요

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/family-tags/{familySpaceId}")
가족 공간 멤버 조회는 제가 하고있어서 이 기능 지워주세요

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @PostMapping("/{userId}")
userId지워주세요

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @PutMapping("/{postId}/{userId}")
userId 여기두요

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @DeleteMapping("/{postId}/{userId}")
userId 여기두요~

2024-07-23 11:39 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/my-posts/{userId}")
userId지워주세요~

2024-07-23 13:37 UTC, dabeann approved these changes

2024-07-23 15:06 UTC, jiinkyung approved these changes

2024-07-23 16:25 UTC, catturtle123 requested changes

2024-07-23 16:25 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +@RequestMapping("/api/v0/post")
s를 붙여야 할 것 같습니다.

2024-07-23 16:25 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/home/{familySpaceId}")
연관관계 상 family space 다음이 post여야 할 것 같습니다.

2024-07-23 16:25 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/detail/{postId}")
detail은 없어도 될 것 같습니다.

2024-07-24 07:55 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/detail/{postId}")
넵! 수정하겠습니다-!

2024-07-24 08:25 UTC, catturtle123 requested changes

2024-07-24 08:25 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/FamilyAlbumController.java
> +    @GetMapping("/{postId}")
앞에 posts 붙여주세요

2024-07-24 08:25 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +    @GetMapping("/{familySpaceId}")
앞에  familySpace 붙어주세요

2024-07-24 11:41 UTC, catturtle123 approved these changes
고생많으셨습니다!

2024-07-24 11:45 UTC, merged