📝 Docs : Auth 관련 Swagger 작성
Like-House/BE pull request #27
Opened 2024-07-20 12:09 UTC by jiinkyung

# 💡 PR Summary - Auth 관련 Swagger 작성

### 📝 Description

---

- 소셜로그인, 로그아웃, 탈퇴 기능 관련 Swagger 작성
- 회원가입 및 로그인 Swagger 보완

### 🌲 Working Branch

---

docs/#22

### 📖 Related Issues

---

#22

### 📚 Etc

---

특이사항

2024-07-20 12:44 UTC, dabeann approved these changes
👍

2024-07-21 12:15 UTC, catturtle123 requested changes

2024-07-21 12:15 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/auth/controller/AuthController.java
> +    @DeleteMapping("/delete")
이미 메소드가 Delete이니 /delete는 필요 없어 보입니다

2024-07-21 13:40 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/auth/controller/AuthController.java
> +    @DeleteMapping("/delete")
수정했습니다~~

2024-07-21 15:01 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-07-21 15:07 UTC, merged