📝 Docs : 유저 정보 설정 Swagger
Like-House/BE pull request #28
Opened 2024-07-20 12:15 UTC by jiinkyung

# 💡 PR Summary - 유저 정보 설정 Swagger 작성

### 📝 Description

---

유저 정보 설정과 관련한 Swagger 작성
- 비밀번호 변경 기능
- 개인정보 수정(프로필 변경, 이름 변경, 생년월일 변경) 기능

### 🌲 Working Branch

---

docs/#23

### 📖 Related Issues

---

#23 

### 📚 Etc

---

비밀번호 수정 기능에서, 새로운 비밀번호를 작성하고 해당 비밀번호를 확인하는 필드에 대한 처리를 서버에서 처리해야 할 지 고민입니다.
우선 현재 비밀번호와 새로운 비밀번호에 대한 필드만 받고 있는데, 확인하는 과정 대한 처리가 필요하다면 추가하도록 하겠습니다.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/76aae561-9856-43c0-b4ae-1d534ad325c5">

2024-07-20 12:46 UTC, dabeann approved these changes
👍

2024-07-21 12:14 UTC, catturtle123 requested changes
현재는 user에만 해놓았는데 다른 부분도 반영하여 수정하여 주세요

2024-07-21 12:14 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/user/controller/UserController.java
> +@RequestMapping("/api/v0/user")
명사에는 s를 붙여주세요

2024-07-21 14:31 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/user/controller/UserController.java
> +@RequestMapping("/api/v0/user")
반영하였습니다~

2024-07-21 15:00 UTC, catturtle123 requested changes

2024-07-21 15:00 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
> +@RequestMapping("/api/v0/schedule")
s를 붙여야할 것 같습니다.

2024-07-21 15:00 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
> +    @PostMapping("/save")
save는 필요없을 것 같습니다.

2024-07-21 15:00 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
> +    @PatchMapping("/modify")
modify는 필요없을 것 같습니다.

2024-07-21 15:00 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
> +    @PostMapping("/check/{userId}")
userId는 토큰으로 받아주세요

2024-07-21 15:00 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/family_space/controller/FamilySpaceController.java
> +    @PostMapping("/generate/{userId}")
generate는 필요 없을 것 같고 userId는 토큰을 사용하여 주세요

2024-07-21 15:06 UTC, jiinkyung commented on src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
> +@RequestMapping("/api/v0/schedule")
제가 코드 병합하면서 다빈님이 커밋하신 내역들이 같이 pr에 반영이 되었네요.. 
해당 부분은 다빈님께 전달 드릴게요~~

저는 User 부분만 확인해주심 감사하겠습니당

2024-07-21 15:26 UTC, dabeann commented on src/main/java/backend/like_house/domain/schedule/controller/ScheduleController.java
> +@RequestMapping("/api/v0/schedule")
준환님이 리뷰 쭉 남기신 것들 반영하겠습니다~

2024-07-21 15:37 UTC, closed without merging