✨ Feature - 소셜로그인 구현
Like-House/BE pull request #63
Opened 2024-07-28 14:31 UTC by jiinkyung

# 💡 PR Summary - 소셜로그인 구현

### 📝 Description

---

카카오, 구글, 네이버에 대한 소셜로그인을 구현하였습니다. 

### 🌲 Working Branch

---

feature/#43

### 📖 Related Issues

---

#43 

### 📚 Etc

---

1. jwt 발급 관련
기존에는 email로 발급 받았으나, socialType도 함께 사용해 jwt를 발급받도록 수정하였습니다.

2. 리팩토링
현재는 rest api 방식으로 구현되어 있습니다. 
oauth2 라이브러리 사용해서 리팩토링 진행하려고 했으나, 잘 안돼서 우선 남은 기능들 구현하고 리팩토링 재시도 해보겠습니다.
소셜 로그인 관련 환경변수 키 값들은 노션에 올려두었습니다~

2024-07-28 15:09 UTC, catturtle123 reviewed
혹시 그러면 email은 이제 unique한 값이 아니게 되는 건가요?

2024-07-28 15:31 UTC, jiinkyung commented
> 혹시 그러면 email은 이제 unique한 값이 아니게 되는 건가요?

넵 그렇게 될 듯 하네요. 
같은 이메일이더라도 socialType(LOCAL, KAKAO, GOOGLE, NAVER)이 다르다면 모두 다른 유저로 구분하도록 했습니다~

2024-07-28 15:33 UTC, catturtle123 approved these changes
넵! 고생하셨습니다

2024-07-28 15:45 UTC, catturtle123 requested changes
Access token을 받는 방식은 보안에 안좋을 수 있습니다

2024-07-28 16:06 UTC, jiinkyung commented
> Access code를 받는 방식은 보안에 안좋을 수 있습니다

넵 ㅠ 그래서 라이브러리 사용해서 구현하려고 했는데 잘 안되어서요..
아니면 현재 상황에서 해당 부분을 보완할 수 있는 방법이 있을까요? 프론트에서 code를 parameter로 전달 받아야 하지 않나요??

2024-07-28 17:14 UTC, catturtle123 commented
Oauth client 방식이 곤란하다면 첫번째는 프론트에서 전부 처리해서 정보만 받는 방법이 있구요. 두번째는 response에 성공 시 넣어주는 방식이 있겠네요.. 일단 이 방식으로 하고 나중에 바꿀까요? (나중에 바꾸면 프론트에게도 말해야해서 프론트에게도 말해야하긴 합니다.)

2024-07-29 00:51 UTC, dabeann approved these changes
👍 수고하셨습니다

2024-07-29 02:45 UTC, jiinkyung commented
> Oauth client 방식이 곤란하다면 첫번째는 프론트에서 전부 처리해서 정보만 받는 방법이 있구요. 두번째는 response에 성공 시 넣어주는 방식이 있겠네요.. 일단 이 방식으로 하고 나중에 바꿀까요? (나중에 바꾸면 프론트에게도 말해야해서 프론트에게도 말해야하긴 합니다.)
> 

네네.. 우선 이렇게 하고 제가 프론트에 담당자분과 이야기 해보겠습니다!

2024-07-29 09:45 UTC, catturtle123 approved these changes
넵! 고생하셨습니다!

2024-07-29 10:52 UTC, jiinkyung commented
oauth client가 안되던 이유를 발견해서 리팩토링 진행하였습니다~
확인하시면 머지하도록 하겠습니다!

2024-07-29 15:16 UTC, merged