✨ Feature : 채팅 구현
Like-House/BE pull request #64
Opened 2024-07-28 15:04 UTC by catturtle123

# 💡 PR Summary - 채팅 구현

### 📝 Description

---

채팅을 위해 소켓 통신, 무한 스크롤 조회 등을 구현하였습니다.

### 🌲 Working Branch

---

feature/#8

### 📖 Related Issues

---

#8 

### 📚 Etc

---

특이사항

2024-07-29 01:02 UTC, dabeann requested changes

2024-07-29 01:02 UTC, dabeann commented on src/main/java/backend/like_house/domain/chatting/service/impl/ChatQueryServiceImpl.java
> +        if (!chatRoomRepository.existsChatRoomById(chatRoomId)) {
chatRoomId로 chat존재하는지 확인하는 어노테이션 추가하는 게 좋아 보입니다!
컨트롤러 부분의 @ LoginUser처럼요~~

2024-07-29 01:03 UTC, dabeann reviewed
그냥 GeneralException 던지는 것 말고 UserException을 따로 만들어서 던지면 뭐가 달라지는건가요 ??

2024-07-29 09:40 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/chatting/service/impl/ChatQueryServiceImpl.java
> +        if (!chatRoomRepository.existsChatRoomById(chatRoomId)) {
chatRoom이 생성될 때 무조건 하나의 chat은 생성이 되기 때문에 괜찮다고 생각합니다!

2024-07-29 09:42 UTC, catturtle123 commented
> 그냥 GeneralException 던지는 것 말고 UserException을 따로 만들어서 던지면 뭐가 달라지는건가요 ??

에러를 따로 나누어서 나중에 advice에서나 try-catch에서 필요할 때 세세하게 나누어서 처리할 수도 있고 스터디북에도 그렇게 되어있었기에 이렇게 처리하였습니다.

2024-07-29 11:04 UTC, dabeann commented
> 에러를 따로 나누어서 나중에 advice에서나 try-catch에서 필요할 때 세세하게 나누어서 처리할 수도 있고 스터디북에도 그렇게 되어있었기에 이렇게 처리하였습니다.

아하~~! 알려주셔서 감사합니다!! 
나중에 저도 리팩토링할 때 적용하도록 하겠습니다

2024-07-29 14:28 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/chatting/service/impl/ChatQueryServiceImpl.java
> +        if (!chatRoomRepository.existsChatRoomById(chatRoomId)) {
> chatRoomId로 chat존재하는지 확인하는 어노테이션 추가하는 게 좋아 보입니다! 컨트롤러 부분의 @ LoginUser처럼요~~

현재 chat이 없을 시 빈 리스트로 나가게금 하였습니다. (생각해보니 chat이 없어도 이상한 동작은 아닐 것 같아서요!)

2024-07-29 14:35 UTC, dabeann approved these changes
수고하셨습니다!

2024-07-30 09:04 UTC, jiinkyung approved these changes
고생하셨습니다 👍

2024-07-30 10:26 UTC, merged