✨ Feature - 게시글 기능 구현
Like-House/BE pull request #69
Opened 2024-07-30 03:35 UTC by haeun1107

# 💡 PR Summary - 게시글 기능 구현 

### 📝 Description

---

게시글 관련 기능 구현

### 🌲 Working Branch

---

feature/#48

### 📖 Related Issues

---

#48 

### 📚 Etc

---

특이사항

2024-07-30 08:24 UTC, catturtle123 requested changes

2024-07-30 08:24 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +        commentRepository.save(comment);
더티 체킹이 되기 때문에 필요 없습니다.

2024-07-30 08:24 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PutMapping("/{commentId}/comment-alarm")
부분 수정이기 때문에 Patch가 좋아보입니다.

2024-07-30 10:19 UTC, dabeann requested changes

2024-07-30 10:19 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +        return ApiResponse.onSuccess(null);
null 반환 대신 String으로 
“알람 끄기/켜기 성공” 처럼 반환하면 좋겠습니다!

2024-07-30 10:19 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +            @RequestParam(required = false, name = "page", defaultValue = "1") @CheckPage Integer page,
CheckPage와 CheckSize넣으셨으니 ApiResponses 에도 에러 뭐 반환하는지 넣어주세요 (스웨거)

2024-07-30 10:19 UTC, dabeann commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +            throw new CommentException(ErrorStatus.INVALID_ACCESS);
INVALID ACCESS에러말고 특정 errorstatus하나 만들어서 반환해주세요

2024-07-30 11:28 UTC, dabeann approved these changes

2024-07-30 11:53 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +        commentRepository.save(comment);
넵!!

2024-07-30 11:53 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PutMapping("/{commentId}/comment-alarm")
수정하겠습니다~!

2024-07-30 11:56 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +        return ApiResponse.onSuccess(null);
네 수정하겠습니다!!

2024-07-30 11:58 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/controller/PostController.java
> +            @RequestParam(required = false, name = "page", defaultValue = "1") @CheckPage Integer page,
네! 알겠습니다~

2024-07-30 12:01 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +            throw new CommentException(ErrorStatus.INVALID_ACCESS);
넵!

2024-07-30 13:16 UTC, jiinkyung approved these changes
고생하셨습니다 👍

2024-07-30 16:45 UTC, catturtle123 requested changes

2024-07-30 16:45 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/service/impl/PostCommandServiceImpl.java
> +        postRepository.save(post);
여기도 save는 필요 없습니다.

2024-07-30 16:45 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +        comment = commentRepository.save(comment);
여기도 필요없습니다.

2024-07-30 16:45 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/controller/CommentController.java
> +    @PutMapping("/{commentId}/comment-alarm")
> 수정하겠습니다~!

여기 아직 반영이 안되었습니다.

2024-07-30 16:48 UTC, catturtle123 commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +        commentRepository.save(comment);
아직 반영이 안되어있습니다

2024-07-30 17:32 UTC, haeun1107 commented on src/main/java/backend/like_house/domain/post/service/impl/CommentCommandServiceImpl.java
> +        comment = commentRepository.save(comment);
반영했습니다..!

2024-07-31 06:07 UTC, catturtle123 approved these changes
넵! 고생하셨습니다

2024-07-31 06:38 UTC, merged